### ISSUE TITLE
LSP fails to start

### ISSUE THREAD

**Issue by ryanslade** [CFiggers/vscode-janet-plus-plus#13]
I'm attempting to use Janet++ in a small project and see this error when the LSP attempts to start:

```
error: nil called with 2 arguments, possibly expected 1
  in <anonymous> [src/main.janet] on line 212, column 13
  in map [boot.janet] on line 998, column 3
  in find-unique-paths [src/main.janet] on line 212, column 8
  in main [src/main.janet] (tailcall) on line 228, column 14
  in run-main [boot.janet] on line 3936, column 16
  in cli-main [boot.janet] on line 4076, column 13
```

I'm running Janet `1.32.1-meson` on Mac OS and VSCode `1.83.1 `

**Comment by CFiggers** [comment]
Thanks for the report. It looks like there's a non-exhaustive `(case)` in Janet LSP's `(find-unique-paths)` function. It dispatches for Windows and Linux, but not Mac OS—definitely an oversight on my part. I'll push an update shortly that should fix it.

**Comment by CFiggers** [comment]
v1.1.0 (#14) should fix this issue—that's now live in the VS Code/Open VSX marketplaces, so you should be able to just update your extension in the editor and let me know if there's still any issues!

**Comment by CFiggers** [comment]
Perfect!

Thank you for submitting this issue. MacOS is the one major platform that I don't have easy access to do testing on, so the only way I would ever have become aware of a problem like this one is thanks to a user report. This problem would have been affecting 100% of other Mac users too. So I'm really glad to have it fixed!

Please do go ahead and open new issues for anything else that comes up!
