### ISSUE TITLE
Wrong indentation for many macros with `& body` args

### ISSUE THREAD

**Issue by jangler** [CFiggers/vscode-janet-plus-plus#18]
The following macros from the core API currently indent like normal tuples rather than like `do`:

- `compwhen`
- `coro`
- `defer`
- `edefer`
- `ev/do-thread`
- `ev/spawn`
- `ev/span-thread`
- `ev/with-deadline`
- `ffi/defbind`
- `fiber-fn`
- `forever`
- `for`
- `forv`
- `generate`
- `label`
- `prompt`
- `protect`
- `repeat`
- `when-with`
- `with`

**Comment by CFiggers** [comment]
Hi @jangler —this is addressed now with pre-release version 1.1.3. Check it out in the Extension Marketplace and let me know if you have any feedback!

**Comment by jangler** [comment]
The ones I tried seem to indent correctly now. Thanks!
