### ISSUE TITLE
Completion suggests incomplete versions of private identifiers

### ISSUE THREAD

**Issue by jangler** [CFiggers/vscode-janet-plus-plus#20]
Create a new Janet file. Type a top-level `def-` binding. Start typing the bound identifier. Incomplete versions of the name appear in the completion list. For instance, if the identifier is `circumference`, completion will suggest `ci`, `cir`, `circ`, `circu`, etc.

**Comment by CFiggers** [comment]
Thanks for reporting! This should be addressed in a forthcoming update to Janet LSP (look out for a new prerelease version over the next ~week).

**Comment by CFiggers** [comment]
Hi there @jangler —this _should_ be fixed now with pre-release version 1.1.3. Check it out in the Extension Marketplace and let me know if you have any feedback!

**Comment by jangler** [comment]
Seems fixed, thanks!
