### ISSUE TITLE
all Janet commands not found on Mac

### ISSUE THREAD

**Issue by incanus** [CFiggers/vscode-janet-plus-plus#29]
I'm trying out the extension and no commands work from the command palette: 

- Evaluate file: `command 'janet.evalFile' not found`
- Start REPL: `command 'janet.startREPL' not found`
- Evaluate expression: `command 'janet.eval' not found`
- Indent line: `command 'janet.calva-fmt.tabIndent` not found`
- etc. 

I've installed Janet in a Mac-standard way using Homebrew, so it's at the standard path (for Apple Silicon) `/opt/homebrew/bin`. At a VS Code terminal, `which janet` or `which janet-netrepl` output correctly. 

Is there something else I need to be doing to get this off the ground from first install? 

Vaguely related to #5, though on a different platform.

**Comment by CFiggers** [comment]
Hi there. Messages saying that commands are not found probably mean that the extension didn't start up correctly, which means some error was probably encountered during the startup process. 

Could you pop open your Dev Tools (command palette "Developer: Toggle Developer Tools") and see if there's any messages highlighted red in the Console (you may need to scroll up to get to the part where Janet++ was initializing)?

**Comment by corrosive4354** [comment]
Homebrew and Mac compatibility bug

I think you can try the [servbay](https://servbay.com) tool, which is more professional on Mac and supports more than homebrew

**Comment by incanus** [comment]
It's now working on one of the two machines I tried on, seemingly randomly. 

The other is still problematic in the same way. Here's what things look like. 

<img width="1912" alt="Screenshot 2024-11-01 at 12 28 22 PM" src="https://github.com/user-attachments/assets/28171bce-2841-4e84-9dd8-f587706b8736">

The seemingly only relevant part, as text: 

```
[Extension Host] Extension "vscode-janet" is activating. console.ts:137
Can't find Janet language on your computer! Check your PATH variable. notificationsAlerts.ts:42 
```

**Comment by CFiggers** [comment]
Yeah, that's about what I would've expected. Check your Path and see if you can make the `janet` executable available to the extension.

Aside from that, I should refactor so that not being able to find the `janet` executable doesn't prevent the extension from initializing...

**Comment by incanus** [comment]
I've been fiddling with this and trying to figure out what's going on, as well as looking through the extension source, however I have not got a local version up & running. 

I also tried symlinking `janet` from `$HOME/bin`, `/usr/local/bin`, etc. to no avail. The extension has only ever worked once for me (save syntax highlighting).

**Comment by CFiggers** [comment]
I borrowed my wife's Mac to experiment and had no problems using brew to install Janet and then run Janet++ in VS Code which needs to be able to find the `janet` executable to run. It started up perfectly on the first try, including launching the bundled Janet LSP, which depends on your installed `janet` to load and run a .jimage file.

Here's the one thing I know for sure: the error you're seeing means that the extension tried to check for the presence of the `janet` executable on your Path and wasn't able to find it. 

I don't know Mac well enough to diagnose much further. But could it be possible that the VS Code process has access to a different Path than your terminal does? Are you using the default ZSH shell in the default Terminal app? Or are you running a different shell like bash or fish or something? Is the mechanism of modifying your path specific to that shell? If your VS Code is running in an environment that doesn't have access to your brew `bin` directory then that could maybe explain it...? Again, really not familiar with macOS.

Hold on, you said it DID work once, but then not again after that...? It's quite weird that it would even work once if there was something broken about it.

**Comment by incanus** [comment]
Thanks @CFiggers for the experimentation and the brainstorming. With your ideas, I may have figured it out. My default shell is Bash; I've been using it for decades and retained it during the Mac switch to ZSH. I did some quick testing involving a `~/.zshrc` and Homebrew and launching VS Code and it all looks promising. I'm guessing the default desktop (i.e. `loginwindow` process) sources the ZSH configuration and provides that to GUI apps. It would explain one or two other things I've noticed including having to provide the Homebrew path for Hammerspoon commands. 

I have no idea how it worked once, but it did. I'm really not sure how. I definitely was having it launch the REPL and evaluate forms and all of that. I'm not as much concerned with that though...

**Comment by CFiggers** [comment]
Glad that seemed to point you in the right direction. 

If you launched code from the terminal with `code .`, then it would probably inherit the path from your bash config rather than the desktop process. 🙂 Might explain why it worked once but then not if you launched VS Code through the GUI.

**Comment by incanus** [comment]
That looks to be it exactly. I just tested on my other machine and could reproduce the problem from GUI launch and not from terminal launch.

Thanks again for the help and sorry to clutter up your issue queue. On the plus side, it’s been my experience that quirks like these often occur again for others, so hopefully having this in the search history will help someone else.  

I’m looking forward to using the extension now!
