### ISSUE TITLE
LSP crashes on macro that prints to output

### ISSUE THREAD

**Issue by jakobhellermann** [CFiggers/vscode-janet-plus-plus#31]
Opening the following file in VSCode crashes the LSP:
```janet
(defmacro repro []
  (print "hi"))

(repro)
```

```
Client Janet Language Server: connection to server is erroring. Header must provide a Content-Length property.
 {"hi\ncontent-length":"62"} Shutting down server.
```

Seems like the compilation output is interspersed with the JSON-RPC stdout, so the the wrong message gets sent to vscode.

**Comment by jakobhellermann** [comment]
it does fix it, thanks :smile:

**Comment by CFiggers** [comment]
Cool! Let me know if you run into anything else 🙂
