### ISSUE TITLE
LSP Debug config setting

### ISSUE THREAD

**Issue by strangepete** [CFiggers/vscode-janet-plus-plus#32]
Hi, this is just a feature request to add a checkbox to the extension settings page to enable the `-d` debug flag for the LSP. Maybe even trigger an LSP reload?

While this is possible using the custom command box, its a little laborious to enter the full path of the extension folder, for example when testing the pre-release as-distributed. And disabling requires clearing the box, each time. An example:

`C:\Users\pete\AppData\Local\Apps\Janet\bin\janet -i C:\Users\pete\.vscode\extensions\calebfiggers.vscode-janet-plus-plus-1.1.7/dist/janet-lsp.jimage --debug`

...obviously not the end of the world, but could be easier. My personal use is to catch the output with `janet-lsp --console`, though one gotcha I can think of is since -debug always logs to a file regardless of remote connection, forgetting to disable the extension setting could result in a very large log file. One solution could be to make forget the flag when vscode is closed, perhaps.

I don't mind trying to do the legwork, though it'll be a learning curve; the lsp/extension.ts doesn't seem too complex...

**Comment by CFiggers** [comment]
Yes, that's a good suggestion that we should implement. If you want to take a shot at it, I'd be happy to review the PR. :) You'll want to:

1. Add the checkbox option to the package.json, then 
2. Add it to the `getConfig()` function in src/config.ts , then 
3. Reference that addition in `src/lsp/extension.ts` where `getConfig()` is being called to access config values. 
 
You can use the existing `--dont-search-jpm-tree` option as a reference for how to get it working.
