### ISSUE TITLE
Highlight of matching parentheses

### ISSUE THREAD

**Issue by GooRoo** [CFiggers/vscode-janet-plus-plus#38]
Hi,

I enjoy writing Janet-code with this extension a lot. But what I noticed is that with Janet++ enabled, I've got no highlight of matching parentheses (although I always had an impression that this is just a default editor feature). When this extension is disabled (either with an official Janet extension or without anything at all), the parentheses are highlighted just fine.

Am I missing something?

**Comment by CFiggers** [comment]
Hi there. Highlighting matching parentheses is turned off by default by Janet++, but you can re-enable it.

Click on the "Janet" filetype indicator in the bottom toolbar of VS Code:

![image](https://github.com/user-attachments/assets/c46b3e19-c0bc-43fb-b325-29366d40ce37)

That will open a popup from the Command Palette (which for me is at the top of the VS Code window). Click on "Configure 'Janet' language based settings..."

![image](https://github.com/user-attachments/assets/4c0224a5-2ef7-496d-9446-f0cef13fdf22)

This will automatically open your user settings.json, insert a new section related to Janet, and pre-populate the defaults that are provided by Janet++. 

![image](https://github.com/user-attachments/assets/8682d82b-870e-41a5-a45c-7dc7f78bfc82)

Change the "editor.matchBrackets" setting from "never" to "always" (and don't forget to click "save") and you should be done!

![image](https://github.com/user-attachments/assets/80d46966-3e5f-49b8-864e-4761b4cfedbe)

**Comment by GooRoo** [comment]
Oh, so that's how it happened. It was overridden on a language level. Thanks!
